/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DailySummaryRouteImport } from './routes/daily-summary'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as NewOrderRouteImport } from './routes/new-order'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as ShiftsRouteImport } from './routes/shifts'
import { Route as UserManagementRouteImport } from './routes/user-management'
import { Route as OrdersIndexRouteImport } from './routes/orders.index'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as OrdersIdReceiptRouteImport } from './routes/orders.$id.receipt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySummaryRoute = DailySummaryRouteImport.update({
  id: '/daily-summary',
  path: '/daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrderRoute = NewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const ShiftsRoute = ShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => rootRouteImport,
} as any)
const UserManagementRoute = UserManagementRouteImport.update({
  id: '/user-management',
  path: '/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdReceiptRoute = OrdersIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => OrdersIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-summary': typeof DailySummaryRoute
  '/inventory': typeof InventoryRoute
  '/menu': typeof MenuRoute
  '/new-order': typeof NewOrderRoute
  '/onboarding': typeof OnboardingRoute
  '/recipes': typeof RecipesRoute
  '/shifts': typeof ShiftsRoute
  '/user-management': typeof UserManagementRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/': typeof OrdersIndexRoute
  '/orders/$id/receipt': typeof OrdersIdReceiptRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-summary': typeof DailySummaryRoute
  '/inventory': typeof InventoryRoute
  '/menu': typeof MenuRoute
  '/new-order': typeof NewOrderRoute
  '/onboarding': typeof OnboardingRoute
  '/recipes': typeof RecipesRoute
  '/shifts': typeof ShiftsRoute
  '/user-management': typeof UserManagementRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders': typeof OrdersIndexRoute
  '/orders/$id/receipt': typeof OrdersIdReceiptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/daily-summary': typeof DailySummaryRoute
  '/inventory': typeof InventoryRoute
  '/menu': typeof MenuRoute
  '/new-order': typeof NewOrderRoute
  '/onboarding': typeof OnboardingRoute
  '/recipes': typeof RecipesRoute
  '/shifts': typeof ShiftsRoute
  '/user-management': typeof UserManagementRoute
  '/orders/$id': typeof OrdersIdRouteWithChildren
  '/orders/': typeof OrdersIndexRoute
  '/orders/$id/receipt': typeof OrdersIdReceiptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/daily-summary'
    | '/inventory'
    | '/menu'
    | '/new-order'
    | '/onboarding'
    | '/recipes'
    | '/shifts'
    | '/user-management'
    | '/orders/$id'
    | '/orders/'
    | '/orders/$id/receipt'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/daily-summary'
    | '/inventory'
    | '/menu'
    | '/new-order'
    | '/onboarding'
    | '/recipes'
    | '/shifts'
    | '/user-management'
    | '/orders/$id'
    | '/orders'
    | '/orders/$id/receipt'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/daily-summary'
    | '/inventory'
    | '/menu'
    | '/new-order'
    | '/onboarding'
    | '/recipes'
    | '/shifts'
    | '/user-management'
    | '/orders/$id'
    | '/orders/'
    | '/orders/$id/receipt'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DailySummaryRoute: typeof DailySummaryRoute
  InventoryRoute: typeof InventoryRoute
  MenuRoute: typeof MenuRoute
  NewOrderRoute: typeof NewOrderRoute
  OnboardingRoute: typeof OnboardingRoute
  RecipesRoute: typeof RecipesRoute
  ShiftsRoute: typeof ShiftsRoute
  UserManagementRoute: typeof UserManagementRoute
  OrdersIdRoute: typeof OrdersIdRouteWithChildren
  OrdersIndexRoute: typeof OrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-summary': {
      id: '/daily-summary'
      path: '/daily-summary'
      fullPath: '/daily-summary'
      preLoaderRoute: typeof DailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-order': {
      id: '/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof NewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shifts': {
      id: '/shifts'
      path: '/shifts'
      fullPath: '/shifts'
      preLoaderRoute: typeof ShiftsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/user-management': {
      id: '/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof UserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/': {
      id: '/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof OrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id/receipt': {
      id: '/orders/$id/receipt'
      path: '/receipt'
      fullPath: '/orders/$id/receipt'
      preLoaderRoute: typeof OrdersIdReceiptRouteImport
      parentRoute: typeof OrdersIdRoute
    }
  }
}

interface OrdersIdRouteChildren {
  OrdersIdReceiptRoute: typeof OrdersIdReceiptRoute
}

const OrdersIdRouteChildren: OrdersIdRouteChildren = {
  OrdersIdReceiptRoute: OrdersIdReceiptRoute,
}

const OrdersIdRouteWithChildren = OrdersIdRoute._addFileChildren(
  OrdersIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DailySummaryRoute: DailySummaryRoute,
  InventoryRoute: InventoryRoute,
  MenuRoute: MenuRoute,
  NewOrderRoute: NewOrderRoute,
  OnboardingRoute: OnboardingRoute,
  RecipesRoute: RecipesRoute,
  ShiftsRoute: ShiftsRoute,
  UserManagementRoute: UserManagementRoute,
  OrdersIdRoute: OrdersIdRouteWithChildren,
  OrdersIndexRoute: OrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
